name: "AccuKnox SAST Scan"
description: "Run AccuKnox SAST scan using accuknox-aspm-scanner"
author: "AccuKnox"
inputs:
  ACCUKNOX_ENDPOINT:
    description: "AccuKnox API endpoint"
    required: true
  ACCUKNOX_TOKEN:
    description: "AccuKnox API token"
    required: true
  ACCUKNOX_LABEL:
    description: "Label for the scan job"
    required: true
  soft_fail:
    description: "Allow pipeline to continue even if scan fails"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Download Scanner
      shell: bash
      run: |
        curl -sSL -o accuknox-aspm-scanner https://github.com/accuknox/accuknox-aspm-scanner/releases/latest/download/accuknox-aspm-scanner-linux-amd64
        chmod +x accuknox-aspm-scanner

    - name: Run SAST Scan
      shell: bash
      run: |
        SOFT_FAIL_ARG=""
        if [ "${{ inputs.soft_fail }}" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        ./accuknox-aspm-scanner scan sast $SOFT_FAIL_ARG \
          --accuknox-endpoint "${{ inputs.ACCUKNOX_ENDPOINT }}" \
          --accuknox-token "${{ inputs.ACCUKNOX_TOKEN }}" \
          --accuknox-label "${{ inputs.ACCUKNOX_LABEL }}"
