name: "AccuKnox SAST Scan"

description: "Run OpenGrep-based SAST scan; results auto-uploaded to CSPM panel."

inputs:
  soft_fail:
    description: "Do not fail the pipeline if scan finds issues"
    required: false
    default: true
  ACCUKNOX_ENDPOINT:
    description: "CSPM panel endpoint URL"
    required: true
  ACCUKNOX_TOKEN:
    description: "Token for authenticating with CSPM panel"
    required: true
  ACCUKNOX_LABEL:
    description: "Label in AccuKnox SaaS for scan results"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox SAST Scan
      shell: bash
      env:
        SOFT_FAIL: ${{ inputs.soft_fail }}
        ACCUKNOX_ENDPOINT: ${{ inputs.ACCUKNOX_ENDPOINT }}
        ACCUKNOX_TOKEN: ${{ inputs.ACCUKNOX_TOKEN }}
        ACCUKNOX_LABEL: ${{ inputs.ACCUKNOX_LABEL }}
      run: |
        # Validate required secrets
        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ]; then
          echo "ERROR: ACCUKNOX_ENDPOINT, ACCUKNOX_TOKEN, and ACCUKNOX_LABEL must be set!"
          exit 1
        fi

        # Download ASPM Scanner
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        # Soft-fail argument
        SOFT_FAIL_ARG=""
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Run SAST scan (OpenGrep)
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG sast \
          --command "." \
          --repo-url "https://github.com/${GITHUB_REPOSITORY}.git" \
          --commit-ref "${GITHUB_REF#refs/heads/}" \
          --commit-sha "$GITHUB_SHA" \
          --pipeline-id "${GITHUB_RUN_ID}" \
          --job-url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
          --accuknox-endpoint "$ACCUKNOX_ENDPOINT" \
          --accuknox-token "$ACCUKNOX_TOKEN" \
          --accuknox-label "$ACCUKNOX_LABEL" \
          --container-mode
